from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

rule all:
    input:
       expand("results/integrated/{split_type}_int.RDS", split_type = ['plate', 'raw']),
       expand("plots/integration/{split_type}_umaps.pdf", split_type = ['plate', 'raw']),
    #    expand('results/sc-data/ref_markers_{CT}.csv', CT = ['cell_type', "cell_subtype"]),
    #    expand('results/integrated/plate_scores_{CT}.csv', CT = ['cell_type', "cell_subtype"]),
       'plots/CTprop/cell2location_umap.pdf'


module preprocess:
    snakefile: 'rules/preprocessing_seurat.smk'
    config: config

use rule * from preprocess as PP_*

module functional:
    snakefile: 'rules/functional.smk'
    config: config

use rule * from functional as Fun_*

module structural:
    snakefile: 'rules/structural.smk'
    config: config

use rule * from structural as St_*


rule merge_adata:
    input:
        adata_w_c2l = 'data/sp.h5ad',
        integrated = "data/integrated/plate_int.h5ad"
    output:
        merged = 'data/merged.h5ad'
    script:
        '../scripts/structural/merge_adata.py'

rule cell_prop:
    input:
        merged = 'data/merged.h5ad',
        dc_CT = 'data/integrated/plate_scores_cell_subtype.csv'
    output:
        c2l = 'plots/CTprop/cell2location_umap.pdf',
        dc = 'plots/CTprop/dc_umap.pdf',
        spat1 = 'plots/CTprop/cell2location_spatial1.pdf',
        spat2 = 'plots/CTprop/cell2location_spatial2.pdf'
    script:
        '../scripts/structural/umaps_CTprop.py'