from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

rule all:
    input:
       expand("results/integrated/{split_type}_int.RDS", split_type = ['plate']),
       expand("plots/integration/{split_type}_umaps.pdf", split_type = ['plate']),
       'plots/structural/plate/cell2location_umap.pdf',
       expand('results/functional/plate/activities_{network}.csv', network = ['pathways', 'cytokines']),
       expand('plots/functional/plate/spatial_activities_{network}.pdf', network = ['pathways', 'cytokines']),
       expand('results/Misty/{view_type}/paraviews.csv', view_type = ['celltype', 'pathwaysCT']),
       expand('results/Misty/{view_type}/models/{sample}', sample = config['samples'], view_type = ['celltype', 'pathwaysCT'])
    #    expand('results/sc-data/ref_markers_{CT}.csv', CT = ['cell_type', "cell_subtype"]),
    #    expand('results/integrated/plate_scores_{CT}.csv', CT = ['cell_type', "cell_subtype"]),
    #    'plots/CTprop/cell2location_umap.pdf'


module preprocess:
    snakefile: 'rules/preprocessing_seurat.smk'
    config: config

use rule * from preprocess as PP_*

module functional:
    snakefile: 'rules/functional.smk'
    config: config

use rule * from functional as Fun_*

module structural:
    snakefile: 'rules/structural.smk'
    config: config

use rule * from structural as St_*

module misty:
    snakefile: 'rules/misty.smk'
    config: config

use rule * from misty as M_*
