from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

rule all:
    input:
       expand('plots/Misty/{view_type}_misty.pdf', view_type = ['celltype']),
       expand('plots/Misty/{view_type}_interaction_correlations.pdf', view_type = ['celltype']),
       'plots/spatial_locations.pdf'


module preprocess:
    snakefile: 'rules/preprocessing_seurat.smk'
    config: config

use rule * from preprocess as PP_*

module functional:
    snakefile: 'rules/functional.smk'
    config: config

use rule * from functional as Fun_*

module structural:
    snakefile: 'rules/structural.smk'
    config: config

use rule * from structural as St_*

module misty:
    snakefile: 'rules/misty.smk'
    config: config

use rule * from misty as M_*
